Fixed readme bug and added suggestion
weapnl/js-junction pull request #20
Opened 2024-03-15 20:59 UTC by TimoCuijpers

The quick start section in the readme has been fixed and suggestions for more clarity are added with comments.

2024-03-25 08:17 UTC, jobjen02 commented on README.md
> +const user = new User().show(1);
const user will be an pending request now. 'await' needs to be added.

2024-03-25 08:17 UTC, jobjen02 commented on README.md
> +const users = new User().index();
const users will be an pending request now. 'await' needs to be added.

2024-03-25 08:17 UTC, jobjen02 commented on README.md
> +const user = new User().show(1);
const user will be an pending request now. 'await' needs to be added.

2024-03-25 08:18 UTC, jobjen02 commented
Also, the changelog needs to be updated.

2024-03-27 14:53 UTC, TimoCuijpers commented on README.md
> +const user = new User().show(1);
Await is only possible when the method where the request is called, is async.

2024-03-27 15:22 UTC, jobjen02 commented on README.md
> +const user = new User().show(1);
The readme is for explanation, not for the full implementation. Right now, the user variable will contain a pending promise, that's why the await needs to be added.

2024-03-27 15:31 UTC, TimoCuijpers commented on README.md
> +const user = new User().show(1);
Okay!

2024-03-27 18:33 UTC, jobjen02 requested changes

2024-03-27 18:33 UTC, jobjen02 commented on package.json
> +  "version": "0.0.10",
Please don't update the version.

2024-03-27 18:33 UTC, jobjen02 commented on CHANGELOG.md
> +- Updated Readme.md
Add this under unreleased.

2024-04-04 13:41 UTC, TimoCuijpers commented on CHANGELOG.md
> +- Updated Readme.md
Okay

2024-04-19 12:31 UTC, robinvda commented on package-lock.json
> +      "version": "0.0.10",
Don't update this. This gets updated when we make a new version.

2024-04-20 20:25 UTC, TimoCuijpers commented on package-lock.json
> +      "version": "0.0.10",
I'm sorry, forking is very new for me.

2024-04-22 06:41 UTC, robinvda approved these changes

2024-04-22 06:41 UTC, merged